#!/bin/bash

EXISTING_CLUSTER=KIND_$(echo $CLUSTER_VERSION | sed -e "s/\./\_/g")
if [[ -z "${EXISTING_CLUSTER}" ]]; then
  kind create cluster --name $1 --image kindest/node:v$CLUSTER_VERSION
else
  echo "Not Creating cluster"
fi
